#!/bin/bash

#script para connectar a rede wifi
1
2
3




#captura nome interface
interface=`ifconfig | grep w | cut -d" " -f1`

#scanneando redes 
if [ -n interface ]; then
  array_ssid=(`iw dev $interface scan | grep -i "SSID" | cut -d: -f2`)
  ssid=`iw dev $interface scan | grep -i "SSID" | cut -d: -f2`
fi

qt=`wc -l << eof
> $ssid
eof` 

for (( i=0; i<=$(( $qt - 1)); i++ ))
do  
 echo "opção: `echo $((i+1))` = " ${array_ssid[@]:$i:1}
done

echo -e "\n Digite o numero da opção da redes:"; read num
clear
echo -e "Você escolheu:  ${array_ssid[@]:(( $num - 1 )):1} \n Digite a Senha: \b ";read num 
